databases:
  - name: baqir
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    name: baqir
    plan: free
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 repth.py & python3 main.py
    region: frankfurt
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: MONGO_DB_URI
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: baqir
          property: connectionString   
    autoDeploy: false
