databases:
  - name: baqir1
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    runtime: python
    name: baqir2
    plan: free
    branch: master
    buildCommand: pip install -U requirements.txt
    startCommand: python3 app.py & python3 main.py
    repo: https://github.com/banen-is-my-love/M.git
    region: frankfurt
    envVars:
      - key: API_ID
        value: 13740761
      - key: API_HASH
        value: 4ce319a92c01fab2b02551af8d7f73a4
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TZ
        value: Asia/Baghdad
      - key: DATABASE_URL
        fromDatabase:
          name: baqir1
          property: connectionString   
    autoDeploy: false
